# Generated by Django 4.1 on 2022-09-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
