# Generated by Django 4.1 on 2022-09-23 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
