# Generated by Django 4.1 on 2022-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_created_ad_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
    ]
